### ISSUE TITLE
libnet80211.a/ieee80211_output.o analysis (&patch)

### ISSUE THREAD

**Issue by valentasn** [mmMikeKn/ESP32-WiFi-tool#4]
I know it's old project but still I'm here banging my head how to patch ieee80211_output.o to bypass ieee80211_raw_frame_sanity_check maybe you can help me to break that wall?

**Comment by P-R-A-Y** [comment]
god will help you

**Comment by valentasn** [comment]
After all I managed to patch that lib 👍
